DROP TABLE IF EXISTS TB_ORDER;
CREATE TABLE TB_ORDER(ID INT PRIMARY KEY AUTO_INCREMENT, ORIGIN VARCHAR(255), TYPE VARCHAR(255), COUNT INT, COST INT);

DROP TABLE IF EXISTS TB_SAGA_EVENT_HISTORY;
CREATE TABLE TB_SAGA_EVENT_HISTORY (ID INT PRIMARY KEY AUTO_INCREMENT, SAGA_ID VARCHAR(255), EVENT_ORIGIN VARCHAR(255), SERVICE_TRANSACTION_ID VARCHAR(255), SAGA_STATUS VARCHAR(255), EVENT_TYPE VARCHAR(255), EVENT_ORDER INT, TIMESTAMP VARCHAR(255));