DROP TABLE IF EXISTS TB_STOCk;
--CREATE TABLE TB_STOCK(ID INT PRIMARY KEY AUTO_INCREMENT, ORIGIN VARCHAR(255), TYPE VARCHAR(255), COUNT INT, COST INT)
CREATE TABLE TB_STOCK(ID INT PRIMARY KEY AUTO_INCREMENT, ORIGIN VARCHAR(255), COUNT INT)